---
- name: Install Tetration agents on Windows nodes
  hosts: win
  become: true
  roles:
    - clean-tetration-sensor-win
    - install-tetration-sensor-win

- name: Install Tetration agents on CentOS nodes
  hosts: centos
  become: true
  roles:
    - clean-tetration-sensor-centos
    - install-tetration-sensor-centos

- name: Install Tetration agents on Ubuntu nodes
  hosts: ubuntu
  remote_user: ubuntu
  become: true
  roles:
    - clean-tetration-sensor-ubuntu
    - install-tetration-sensor-ubuntu

